### ISSUE TITLE
Make decision on collective git workflow with other teams

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#100]
This is primarily a discussion that needs to happen with the other teams.  We need to adopt a git workflow/branching model that is better suited to our growing teams.  Recommendations and reasoning behind this (and discussion points) can be found here:

https://docs.google.com/document/d/1Q6-rOGDPgBl1lmWQgS9CLZoVwGkKqmj9CuEAzb2cgiI/edit?usp=sharing

Outside of making a decision as a team, there will be some technical tasks that will be required to put this into action.  This should involve creating the greater (project-level) branches, establishing branch-permissions within github, and running test PR/Merges to ensure that its been properly setup before any significant development against it starts.

Acceptance Criteria:
- Project team collectively decides on a Git Workflow / Branching Strategy for the project

**Comment by bsnopek-freshworks** [comment]
@ConradGustafson @sienna-freshworks @nisha-agrawal - This should be complete now, correct ? it wasn't estimated or assigned ot a sprint - but I do believe as of now its completed.

**Comment by bsnopek-freshworks** [comment]
@ConradGustafson @sienna-freshworks @nisha-agrawal PING

**Comment by sienna-freshworks** [comment]
Closing!
