### ISSUE TITLE
DEVOPS - Setup the pipelines (Jenkins or Github Actions)

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#101]
Open shift will need to be setup to facilitate the building and testing of all components.  Its not yet been decided if we are going to use Jenkins (in openshift) or if we are going to use Github's Actions (and BCDevOps prototype for it). Either way, we need to provision the environments and configuration manifests, similar to what has already been done for the entities team, but with the adoption of the BCDevOps Pipeline model.

See: https://github.com/BCDevOps/ocp-cd-pipeline

This model helps ensures that when a pull request is made, it creates a hash of the component-directories and openshift-configuration, and only redeploys component (pods) that have a differing hash from what is currently deployed.  This helps ensure that we can keep the 'jobs' minimal and fully encompassing of the project, while reducing the build time and effectiveness of the job.

Note:
This could be a combination of Jenkins AND Github actions - Jenkins will be required for sure, but we might want to do some early PR testing / reporting in actions.

Acceptance Criteria
- Pipeline process setup for automatic builds on pull requests

**Comment by bsnopek-freshworks** [comment]
Jenkins has been setup in openshift, with the following completed:
- Built entirely as infrastructure/configuration as code and stored in source control.
- Utilizes openshift as auth
- Deployed 'tools' and service accounts created for deployment to dev/test/prod
- Linked with Github via webhooks, reports back to github with build status
- Currently starts a job on PR, and runs cleanup on PR close.

TODO STILL:
- Create bc/dc docker-builds for each component and add to the jenkins file.
