### ISSUE TITLE
UI & Func - Implement functionality to "reset" my drafted record office changes

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#131]
## Description:
Using the same functionality that was built for canceling / reverting changes made to registered office addresses for Coops, we will be doing the same thing for record office address changes.

**Acceptance Criteria:**
* Similar to registered office address functionality, when the user chooses to revert their changes, the UI updates to show the original record office addresses that were fetched from the database when the page loaded.

**Developer Notes:**
* Reuse the same functionality in our new modified Addresses component.
* Fetch the address from the database
 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
included in Record Office Address ticket. Closing
