### ISSUE TITLE
SPIKE - Modularization (Back-end)

### ISSUE THREAD

**Issue by sienna-freshworks** [bcgov/fwben#31]
## Description:  
Investigate code and best method to implement modularization for Annual Reports. Document results and then create the relevant additional tickets.

**Definition of Ready:**
- [ ] Stakeholders have approved research (including other teams)
- [ ] Questions still unanswered

**Definition of Done:**
- [ ] Research peer-reviewed 
- [ ] Research documented
- [ ] New tickets made if relevant
- [ ] Stakeholders have approved research (including other teams)

**Comment by nisha-agrawal** [comment]
This was not required to be completed, as modularization is not quite relevant for the backend process.
