### ISSUE TITLE
UI - AR Summary Screen

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#46]
## Description:
As a user, I can view a summary of my AR filing before paying, so that I can confirm that I have entered everything correctly.

**Acceptance Criteria:**
* Given i am logged in (as a bcorp or co-op), when i finish entering everything needed for an AR, then i can view a summary of the information that i filed.
* Screen matches the design
 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] ~E2E tests created and passing~
- [ ] Code review completed
- [ ] ~Test cases created and passing~
- [ ] ~Regression tests passing~
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
No longer in scope!
