### ISSUE TITLE
Functionality - Generate AR summary info

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#47]
## Description:
After making all the updates to the AR, the user will go to a summary screen. This screen displays all the changes that they made to all the available fields. Grab the real draft filing data from _wherever it is_ and show it on this screen.
Also, add the "certify" button functionality

**Acceptance Criteria:**
* Given i am logged in, when i enter all info needed tofile my AR, then i am able to view a summary screen of everything i filled in before i submit.
 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
No longer in scope!
