### ISSUE TITLE
UI - Summary certification component

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#51]
## Description:
The summary screen has a certification component that uses the user's legal name entered above it which allows them to certify that they are allowed to file the AR.

##Developer Notes:
The current AR filing flow has a certification component, which will now be move to the summary screen instead.

**Acceptance Criteria:**
* The certification component is displayed beneath the legal name input component on the summary screen instead of on the AR filing screen
* The user can check a checkbox to certify that they are allowed to submit the filing
 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
included in summary screen ticket. closing.
