### ISSUE TITLE
UI - Build officers component to display existing officer data

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#54]
## Description:
Using existing functionality of directors, there needs to be a way for a user to add officers. The user should be able to see the existing officers before deciding to add/remove/edit an officer.

**Acceptance Criteria:**

 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
Decision made by policy, no longer required
