### ISSUE TITLE
Functionality - Fetch existing officers' data

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#55]
## Description:
In order to display potential existing officers while filing the AR, the data for all current officers needs to be fetched.

**Acceptance Criteria:**

 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
Decision made by policy, no longer required
