### ISSUE TITLE
UI - Add an officer based on directors

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#57]
## Description:
Based on the functionality for adding a director, build the UI to add an officer who has a name, address and office held.

**Acceptance Criteria:**

 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
Decision made by policy, no longer required
