### ISSUE TITLE
UI - Build interface for removing an officer based on directors

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#61]
## Description:
Based on the functionality for removing a director, the user should be able to remove an officer.

**Acceptance Criteria:**

 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
Decision made by policy, no longer required
