### ISSUE TITLE
Functionality - Revert any changes made to officers based on directors

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#64]
## Description:
When a user clicks the reset button, the information entered for officers will revert to the latest information that was fetched from the database when the AR filing screen loaded.

**Acceptance Criteria:**

 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
Decision made by policy, no longer required
