### ISSUE TITLE
Functionality - Remove a director's delivery address when the director is removed

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#78]
## Description:
Functionality already exists to remove a director. We need to make sure that the director's delivery address is also removed when the director is removed.

**Acceptance Criteria:**

 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
Closing because this functionality has already been implemented
