### ISSUE TITLE
Design - Edit record office addresses

### ISSUE THREAD

**Issue by sienna-freshworks** [bcgov/fwben#80]
### As a user, I want to edit the Record Office Mailing + Deliver addresses, while filing my AR.

* This has already been designed mostly [see Co-ops designs](https://invis.io/MHTDPV2Z4GS#/378880649_File_-_Edit_Office_Address)
* Record office mailing & delivery addresses contain all the same standard address fields (as shown in the designs above)

**Acceptance Criteria**
* Analyze if any additional design is needed for editing a record office mailing and delivery address
* Create designs if needed

**Comment by billin-yu** [comment]
Some format as Registered Office Addresses. 
Option A - Have Record Office and Registered Office separate. 
Option B - Have them combined, because the fee will be only added once regardless of changing office address or record office.
